version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
       - ./sql/DDL.sql:/docker-entrypoint-initdb.d/DDL.sql
    environment:
      POSTGRES_USER: gov
      POSTGRES_PASSWORD: gov

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 